
////
This file is generated! See _meta/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
= Exported Fields

[partintro]

--
This document describes the fields that are exported by Nessusbeat. They are
grouped in the following categories:

* <<exported-fields-beat>>
* <<exported-fields-cloud>>
* <<exported-fields-kubernetes-processor>>
* <<exported-fields-nessusbeat>>

--
[[exported-fields-beat]]
== Beat Fields

Contains common beat fields available in all event types.



[float]
=== beat.name

The name of the Beat sending the log messages. If the Beat name is set in the configuration file, then that value is used. If it is not set, the hostname is used. To set the Beat name, use the `name` option in the configuration file.


[float]
=== beat.hostname

The hostname as returned by the operating system on which the Beat is running.


[float]
=== beat.timezone

The timezone as returned by the operating system on which the Beat is running.


[float]
=== beat.version

The version of the beat that generated this event.


[float]
=== @timestamp

type: date

example: August 26th 2016, 12:35:53.332

format: date

required: True

The timestamp when the event log record was generated.


[float]
=== tags

Arbitrary tags that can be set per Beat and per transaction type.


[float]
=== fields

type: object

Contains user configurable fields.


[float]
== error Fields

Error fields containing additional info in case of errors.



[float]
=== error.message

type: text

Error message.


[float]
=== error.code

type: long

Error code.


[float]
=== error.type

type: keyword

Error type.


[[exported-fields-cloud]]
== Cloud Provider Metadata Fields

Metadata from cloud providers added by the add_cloud_metadata processor.



[float]
=== meta.cloud.provider

example: ec2

Name of the cloud provider. Possible values are ec2, gce, or digitalocean.


[float]
=== meta.cloud.instance_id

Instance ID of the host machine.


[float]
=== meta.cloud.instance_name

Instance name of the host machine.


[float]
=== meta.cloud.machine_type

example: t2.medium

Machine type of the host machine.


[float]
=== meta.cloud.availability_zone

example: us-east-1c

Availability zone in which this host is running.


[float]
=== meta.cloud.project_id

example: project-x

Name of the project in Google Cloud.


[float]
=== meta.cloud.region

Region in which this host is running.


[[exported-fields-kubernetes-processor]]
== kubernetes Fields

beta[]
Kubernetes metadata added by the kubernetes processor




[float]
=== kubernetes.pod.name

type: keyword

Kubernetes pod name


[float]
=== kubernetes.namespace

type: keyword

Kubernetes namespace


[float]
=== kubernetes.labels

type: object

Kubernetes labels map


[float]
=== kubernetes.annotations

type: object

Kubernetes annotations map


[float]
=== kubernetes.container.name

type: keyword

Kubernetes container name


[float]
=== kubernetes.container.image

type: keyword

Kubernetes container image


[[exported-fields-nessusbeat]]
== nessusbeat Fields

None


[float]
=== plugin_id

type: long

[float]
=== cve

type: text

[float]
=== cvss

type: text

[float]
=== risk

type: text

[float]
=== host

type: text

[float]
=== protocol

type: text

[float]
=== port

type: long

[float]
=== name

type: text

[float]
=== synopsis

type: text

[float]
=== description

type: text

[float]
=== solution

type: text

[float]
=== see_also

type: text

[float]
=== plugin_output

type: text

